[profile.default]
solc = "0.8.17"
fs_permissions = [{ access = "read", path = "./permit2/out/Permit2.sol/Permit2.json"}, { access = "read", path = "./tests/forge/interop.json"}]
src = "./tests/forge"
via_ir = true
